// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizzéria.Models;

#nullable disable

namespace Pizzéria.Migrations
{
    [DbContext(typeof(PizzaATDB))]
    [Migration("20240526230306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Pizzéria.Models.PizzaAT", b =>
                {
                    b.Property<int>("IdAT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionAT")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomAT")
                        .HasColumnType("TEXT");

                    b.HasKey("IdAT");

                    b.ToTable("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
